// flow-typed signature: e92ffd61e65ad9912f6dc379c9642bdc
// flow-typed version: <<STUB>>/ionicons-npm_v^2.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons-npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons-npm' {
  declare module.exports: any;
}
